### ISSUE TITLE
3d_MRI.ipynb: Out of memory error -- is there a way to reduce the batch size or similar?

### ISSUE THREAD

**Issue by sck** [tancik/fourier-feature-networks#2]
I am trying to run 3d_MRI.ipynb locally but I haven't found any way to adjust the memory usage.  There isn't an obvious batch_size variable -- any hints?

Thanks!

**Comment by pratulsrinivasan** [comment]
Ah yeah sorry the 3D MRI experiments use a lot of GPU memory. The batch_size is actually the total number of voxels (x_train) since you need all the samples in order to take the Fourier transform to compute the loss. One way to reduce memory usage is to just decrease the voxel grid resolution (RES).
